# Generated by Django 2.2 on 2019-04-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='year',
            field=models.DateField(),
        ),
    ]
