# Generated by Django 2.2 on 2019-04-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_auto_20190413_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='year',
            field=models.IntegerField(),
        ),
    ]
